SELECT c.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS pk
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE c ON pk.CONSTRAINT_NAME = c.CONSTRAINT_NAME
WHERE pk.TABLE_NAME = 'Books' AND CONSTRAINT_TYPE = 'PRIMARY KEY';
